In [1]:
import numpy as np

# 원본 행렬 R 생성, 분해 행렬 P와 Q 초기화, 잠재 요인 차원 K는 3으로 설정
R = np.array([[4, np.NaN, np.NaN, 2, np.NaN],
             [np.NaN, 5, np.NaN, 3, 1],
             [np.NaN, np.NaN, 3, 4, 4],
             [5,2,1,2,np.NaN]])

num_users, num_items = R.shape
K=3

# P와 Q 행렬의 크기를 지정하고 정규 분포를 가진 임의의 값으로 입력
np.random.seed(1)
P = np.random.normal(scale=1./K, size=(num_users, K))
Q = np.random.normal(scale=1./K, size=(num_items, K))

In [2]:
from sklearn.metrics import mean_squared_error

def get_rmse(R, P, Q, non_zeros):
    error = 0
    # 두 개의 분해된 행렬 P와 Q.T의 내적으로 예측 R 행렬 생성
    full_pred_matrix = np.dot(P, Q.T)
    
    # 실제 R 행렬에서 널이 아닌 값의 위치 인덱스 추출해 실제 R 행렬과 예측 행렬의 RMSE 추출
    x_non_zero_ind = [non_zero[0] for non_zero in non_zeros]
    y_non_zero_ind = [non_zero[1] for non_zero in non_zeros]
    R_non_zeros = R[x_non_zero_ind, y_non_zero_ind]
    full_pred_matrix_non_zeros = full_pred_matrix[x_non_zero_ind, y_non_zero_ind]
    mse = mean_squared_error(R_non_zeros, full_pred_matrix_non_zeros)
    rmse = np.sqrt(mse)
    
    return rmse

In [4]:
# R > 0인 행 위치, 열 위치, 값을 non_zeros 리스트에 저장
non_zeros = [ (i, j, R[i,j]) for i in range(num_users) for j in range(num_items) if R[i,j]>0]

steps = 1000
learning_rate = 0.01
r_lambda = 0.01

# SGD 기법으로 P와 Q 매트릭스를 계속 업데이트
for step in range(steps):
    for i, j, r in non_zeros:
        # 실제 값과 예측 값의 차이인 오류 값 구함
        eij = r - np.dot(P[i, :], Q[j, :].T)
        # Regularization을 반영한 SGD 업데이트 공식 적용
        P[i, :] = P[i, :] + learning_rate*(eij * Q[j, :] - r_lambda*P[i, :])
        Q[j, :] = Q[j, :] + learning_rate*(eij * P[i, :] - r_lambda*Q[j, :])
        
        rmse = get_rmse(R, P, Q, non_zeros)
        if (step % 50) == 0:
            print('### iteration step: ', step, ' rmse: ', rmse)

### iteration step:  0  rmse:  3.259459570920174
### iteration step:  0  rmse:  3.2585295271131973
### iteration step:  0  rmse:  3.2521099280637533
### iteration step:  0  rmse:  3.250301384821969
### iteration step:  0  rmse:  3.2504784118719807
### iteration step:  0  rmse:  3.2492149633392726
### iteration step:  0  rmse:  3.247385782225293
### iteration step:  0  rmse:  3.245556255980146
### iteration step:  0  rmse:  3.2401598629557324
### iteration step:  0  rmse:  3.2382931118523164
### iteration step:  0  rmse:  3.238413055138202
### iteration step:  0  rmse:  3.2370465747107744
### iteration step:  50  rmse:  0.5015004152105822
### iteration step:  50  rmse:  0.5013163339724306
### iteration step:  50  rmse:  0.5001971542619058
### iteration step:  50  rmse:  0.5000256311100154
### iteration step:  50  rmse:  0.5001282058216056
### iteration step:  50  rmse:  0.4994928628629658
### iteration step:  50  rmse:  0.49959027043603593
### iteration step:  50  rmse:  0.49910871647594846
### iteration step:  50  rmse:  0.4911906296475222
### iteration step:  50  rmse:  0.4902602272231556
### iteration step:  50  rmse:  0.4898833189303622
### iteration step:  50  rmse:  0.48884683353843905
### iteration step:  100  rmse:  0.1656404247698923
### iteration step:  100  rmse:  0.1653730060332577
### iteration step:  100  rmse:  0.16531818830007153
### iteration step:  100  rmse:  0.16487576903524917
### iteration step:  100  rmse:  0.1648965052250993
### iteration step:  100  rmse:  0.1648654241400033
### iteration step:  100  rmse:  0.16444864298141992
### iteration step:  100  rmse:  0.16449513044583444
### iteration step:  100  rmse:  0.16381593166875422
### iteration step:  100  rmse:  0.16369378971915738
### iteration step:  100  rmse:  0.1634549506271301
### iteration step:  100  rmse:  0.16295696042078667
### iteration step:  150  rmse:  0.08115662025806143
### iteration step:  150  rmse:  0.0811528866085065
### iteration step:  150  rmse:  0.08114452526534727
### iteration step:  150  rmse:  0.08086252251267534
### iteration step:  150  rmse:  0.08090104399080414
### iteration step:  150  rmse:  0.08093638992367712
### iteration step:  150  rmse:  0.08060622202805807
### iteration step:  150  rmse:  0.08064765606254354
### iteration step:  150  rmse:  0.0803161978392446
### iteration step:  150  rmse:  0.08032915042982565
### iteration step:  150  rmse:  0.08032466606941722
### iteration step:  150  rmse:  0.08020066824119743
### iteration step:  200  rmse:  0.047804551705241255
### iteration step:  200  rmse:  0.04789347853190011
### iteration step:  200  rmse:  0.04788137350159885
### iteration step:  200  rmse:  0.047660904712863765
### iteration step:  200  rmse:  0.047713713065170346
### iteration step:  200  rmse:  0.04777214938408408
### iteration step:  200  rmse:  0.047485758200688316
### iteration step:  200  rmse:  0.047510297575279116
### iteration step:  200  rmse:  0.04726616735326988
### iteration step:  200  rmse:  0.047291443400169525
### iteration step:  200  rmse:  0.04729442162018799
### iteration step:  200  rmse:  0.047397183673063295
### iteration step:  250  rmse:  0.03232722891322602
### iteration step:  250  rmse:  0.03245367061217704
### iteration step:  250  rmse:  0.03242128301518024
### iteration step:  250  rmse:  0.03223884706369809
### iteration step:  250  rmse:  0.03230743667003828
### iteration step:  250  rmse:  0.03237156844561531
### iteration step:  250  rmse:  0.032104729318482406
### iteration step:  250  rmse:  0.03211424471496353
### iteration step:  250  rmse:  0.03188484662194639
### iteration step:  250  rmse:  0.031924684562491916
### iteration step:  250  rmse:  0.03192613777182932
### iteration step:  250  rmse:  0.03213581083091953
### iteration step:  300  rmse:  0.024671619524324794
### iteration step:  300  rmse:  0.02481099505271568
### iteration step:  300  rmse:  0.024751962043613077
### iteration step:  300  rmse:  0.024597938463634665
### iteration step:  300  rmse:  0.02468141167546352
### iteration step:  300  rmse:  0.024741120114817217
### iteration step:  300  rmse:  0.024488407897508644
### iteration step:  300  rmse:  0.024487411853467624
### iteration step:  300  rmse:  0.024244286675337883
### iteration step:  300  rmse:  0.02430567704607989
### iteration step:  300  rmse:  0.024322759711726646
### iteration step:  300  rmse:  0.024577612755883164
### iteration step:  350  rmse:  0.0208887833359502
### iteration step:  350  rmse:  0.021027973816665217
### iteration step:  350  rmse:  0.020944540081270672
### iteration step:  350  rmse:  0.020813013221265362
### iteration step:  350  rmse:  0.020907666224993064
### iteration step:  350  rmse:  0.020957851458533298
### iteration step:  350  rmse:  0.020719858426921492
### iteration step:  350  rmse:  0.02071214509517167
### iteration step:  350  rmse:  0.02044886296703833
### iteration step:  350  rmse:  0.020531158631629905
### iteration step:  350  rmse:  0.02056837367763967
### iteration step:  350  rmse:  0.020838065421840374
### iteration step:  400  rmse:  0.019035030668861707
### iteration step:  400  rmse:  0.019168043034415116
### iteration step:  400  rmse:  0.019066644511679408
### iteration step:  400  rmse:  0.018951983296034366
### iteration step:  400  rmse:  0.01905360149382787
### iteration step:  400  rmse:  0.019093823660413744
### iteration step:  400  rmse:  0.018870189821573808
### iteration step:  400  rmse:  0.018858414977478092
### iteration step:  400  rmse:  0.018578357743770396
### iteration step:  400  rmse:  0.01867634393094568
### iteration step:  400  rmse:  0.018729775475515197
### iteration step:  400  rmse:  0.01900125090799809
### iteration step:  450  rmse:  0.01811319096270042
### iteration step:  450  rmse:  0.01823857491523978
### iteration step:  450  rmse:  0.01812539361585301
### iteration step:  450  rmse:  0.01802246245437427
### iteration step:  450  rmse:  0.018128031551534855
### iteration step:  450  rmse:  0.018160224344623672
### iteration step:  450  rmse:  0.01794861802130369
### iteration step:  450  rmse:  0.01793438513953005
### iteration step:  450  rmse:  0.017642571025706304
### iteration step:  450  rmse:  0.017750894020664227
### iteration step:  450  rmse:  0.017815198990271792
### iteration step:  450  rmse:  0.018084557702152983
### iteration step:  500  rmse:  0.017636319556265538
### iteration step:  500  rmse:  0.01775466126024632
### iteration step:  500  rmse:  0.01763405236901508
### iteration step:  500  rmse:  0.017538937931404857
### iteration step:  500  rmse:  0.017646733371423824
### iteration step:  500  rmse:  0.017673192983038384
### iteration step:  500  rmse:  0.01747071710910285
### iteration step:  500  rmse:  0.01745491240731675
### iteration step:  500  rmse:  0.01715516584882119
### iteration step:  500  rmse:  0.017269996596103655
### iteration step:  500  rmse:  0.017341119844339406
### iteration step:  500  rmse:  0.017608110115141726
### iteration step:  550  rmse:  0.01737472440303063
### iteration step:  550  rmse:  0.017487167760428128
### iteration step:  550  rmse:  0.017361838367915324
### iteration step:  550  rmse:  0.01727190930272692
### iteration step:  550  rmse:  0.017381026711136338
### iteration step:  550  rmse:  0.01740360027341225
### iteration step:  550  rmse:  0.01720775630834828
### iteration step:  550  rmse:  0.017190863121329555
### iteration step:  550  rmse:  0.016885670784227088
### iteration step:  550  rmse:  0.01700462024110756
### iteration step:  550  rmse:  0.017079978867646648
### iteration step:  550  rmse:  0.017345264338097074
### iteration step:  600  rmse:  0.01721979991862272
### iteration step:  600  rmse:  0.01732745837395182
### iteration step:  600  rmse:  0.01719901119270622
### iteration step:  600  rmse:  0.01711261726045139
### iteration step:  600  rmse:  0.017222589794479538
### iteration step:  600  rmse:  0.0172425672130213
### iteration step:  600  rmse:  0.017051493545524182
### iteration step:  600  rmse:  0.017033785862638214
### iteration step:  600  rmse:  0.016724720513753524
### iteration step:  600  rmse:  0.01684637129696395
### iteration step:  600  rmse:  0.016924418318819686
### iteration step:  600  rmse:  0.01718862798318347

### iteration step:  650  rmse:  0.017118869568523373
### iteration step:  650  rmse:  0.01722266678556083
### iteration step:  650  rmse:  0.01709203443642192
### iteration step:  650  rmse:  0.017008178904430824
### iteration step:  650  rmse:  0.017118761890431516
### iteration step:  650  rmse:  0.01713699084091431
### iteration step:  650  rmse:  0.016949381919718273
### iteration step:  650  rmse:  0.016931025126864934
### iteration step:  650  rmse:  0.016619100253349818
### iteration step:  650  rmse:  0.016742624578433122
### iteration step:  650  rmse:  0.016822451331407067
### iteration step:  650  rmse:  0.017085979050797395
### iteration step:  700  rmse:  0.017045566217993385
### iteration step:  700  rmse:  0.01714623006482441
### iteration step:  700  rmse:  0.017013952393410938
### iteration step:  700  rmse:  0.01693204580061433
### iteration step:  700  rmse:  0.017043107771740035
### iteration step:  700  rmse:  0.017060131494898805
### iteration step:  700  rmse:  0.01687508971640985
### iteration step:  700  rmse:  0.016856190590676706
### iteration step:  700  rmse:  0.016542081465042536
### iteration step:  700  rmse:  0.016666997075212363
### iteration step:  700  rmse:  0.016748071893810508
### iteration step:  700  rmse:  0.017011105345954243
### iteration step:  750  rmse:  0.016986339809632493
### iteration step:  750  rmse:  0.017084436967500193
### iteration step:  750  rmse:  0.01695082628138862
### iteration step:  750  rmse:  0.016870524317940876
### iteration step:  750  rmse:  0.016981992777462044
### iteration step:  750  rmse:  0.01699815722392501
### iteration step:  750  rmse:  0.016815064431302793
### iteration step:  750  rmse:  0.016795696244363934
### iteration step:  750  rmse:  0.01647986952726747
### iteration step:  750  rmse:  0.016605894622770664
### iteration step:  750  rmse:  0.01668790580708602
### iteration step:  750  rmse:  0.016950496321183166
### iteration step:  800  rmse:  0.016934119095486123
### iteration step:  800  rmse:  0.01703009266403215
### iteration step:  800  rmse:  0.01689533009636592
### iteration step:  800  rmse:  0.01681643299125965
### iteration step:  800  rmse:  0.016928266913398868
### iteration step:  800  rmse:  0.01694379364389857
### iteration step:  800  rmse:  0.016762218228952026
### iteration step:  800  rmse:  0.016742433865408492
### iteration step:  800  rmse:  0.016425223785991577
### iteration step:  800  rmse:  0.0165521925558417
### iteration step:  800  rmse:  0.016634956416681307
### iteration step:  800  rmse:  0.01689707730773566
### iteration step:  850  rmse:  0.016885209229714936
### iteration step:  850  rmse:  0.016979409506174308
### iteration step:  850  rmse:  0.016843600907177805
### iteration step:  850  rmse:  0.01676599280752178
### iteration step:  850  rmse:  0.016878168291140586
### iteration step:  850  rmse:  0.01689320133872485
### iteration step:  850  rmse:  0.01671283569006169
### iteration step:  850  rmse:  0.016692674864229467
### iteration step:  850  rmse:  0.016374328978202374
### iteration step:  850  rmse:  0.016502142600004453
### iteration step:  850  rmse:  0.016585549893261213
### iteration step:  850  rmse:  0.01684713557271282
### iteration step:  900  rmse:  0.016837711763542366
### iteration step:  900  rmse:  0.01693041931257471
### iteration step:  900  rmse:  0.016793627638952178
### iteration step:  900  rmse:  0.01671724068566277
### iteration step:  900  rmse:  0.016829743262746093
### iteration step:  900  rmse:  0.01684437846757821
### iteration step:  900  rmse:  0.016664998056375946
### iteration step:  900  rmse:  0.016644491504265693
### iteration step:  900  rmse:  0.01632519889523052
### iteration step:  900  rmse:  0.016453797081559078
### iteration step:  900  rmse:  0.016537781778027245
### iteration step:  900  rmse:  0.016798751422296237
### iteration step:  950  rmse:  0.01679069355652949
### iteration step:  950  rmse:  0.016882136002329223
### iteration step:  950  rmse:  0.016744400074734395
### iteration step:  950  rmse:  0.016669193347642577
### iteration step:  950  rmse:  0.01678201376947263
### iteration step:  950  rmse:  0.016796316919656516
### iteration step:  950  rmse:  0.016617753766132688
### iteration step:  950  rmse:  0.01659692581436572
### iteration step:  950  rmse:  0.016276834926868926
### iteration step:  950  rmse:  0.016406179382436374
### iteration step:  950  rmse:  0.016490700427972228
### iteration step:  950  rmse:  0.016750971303799066

In [5]:
pred_matrix = np.dot(P, Q.T)
print('예측 행렬:\n', np.round(pred_matrix, 3))

예측 행렬:
 [[3.99  0.783 1.341 2.003 1.729]
 [6.702 4.978 0.953 2.98  1.003]
 [6.933 0.42  2.987 3.976 3.986]
 [4.968 2.005 1.007 2.018 1.163]]

In [14]:
import pandas as pd
import numpy as np
import warnings; warnings.filterwarnings('ignore')

movies = pd.read_csv('./tmdb_5000_movies.csv')
print(movies.shape)
movies.head(1)

(4803, 20)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""name"": ""Fantasy""}, {...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"": 2964, ""name"": ""future""}, {""id"": 3386, ""name"": ""sp...",en,Avatar,"In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, ...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289}, {""name"": ""Twentieth Century Fox Film Corporatio...","[{""iso_3166_1"": ""US"", ""name"": ""United States of America""}, {""iso_3166_1"": ""GB"", ""name"": ""United ...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso_639_1"": ""es"", ""name"": ""Espa\u00f1ol""}]",Released,Enter the World of Pandora.,Avatar,7.2,11800

In [15]:
movies_df = movies[['id', 'title', 'genres', 'vote_average', 'vote_count', 'popularity', 'keywords', 'overview']]

In [16]:
pd.set_option('max_colwidth', 100)
movies_df[['genres', 'keywords']][:1]

,genres,keywords
0,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""name"": ""Fantasy""}, {...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"": 2964, ""name"": ""future""}, {""id"": 3386, ""name"": ""sp..."

In [17]:
from ast import literal_eval
movies_df['genres'] = movies_df['genres'].apply(literal_eval)
movies_df['keywords'] = movies_df['keywords'].apply(literal_eval)

In [18]:
movies_df['genres'] = movies_df['genres'].apply(lambda x: [y['name'] for y in x])
movies_df['keywords'] = movies_df['keywords'].apply(lambda x: [y['name'] for y in x])
movies_df[['genres', 'keywords']][:1]

,genres,keywords
0,"[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colony, society, space travel, futuristic, romance, spa..."

In [23]:
from sklearn.feature_extraction.text import CountVectorizer

# CountVectorizer를 적용하기 위해 공백문자로 word 단위가 구분되는 문자열로 변환
movies_df['genres_literal'] = movies_df['genres'].apply(lambda x: (' ').join(x))
count_vect = CountVectorizer(min_df=0, ngram_range=(1,2))
genre_mat = count_vect.fit_transform(movies_df['genres_literal'])
print(genre_mat.shape)

(4803, 276)

In [24]:
from sklearn.metrics.pairwise import cosine_similarity

genre_sim = cosine_similarity(genre_mat, genre_mat)
print(genre_sim.shape)
print(genre_sim[:1])

(4803, 4803)
[[1.         0.59628479 0.4472136  ... 0.         0.         0.        ]]

In [25]:
genre_sim_sorted_ind = genre_sim.argsort()[:, ::-1]
print(genre_sim_sorted_ind[:1])

[[   0 3494  813 ... 3038 3037 2401]]

In [26]:
def find_sim_movie(df, sorted_ind, title_name, top_n=10):
    # 인자로 입력된 movies_df DataFrame에서 'title' 칼럼이 입력된 title_name 값인 DataFrame 추출
    title_movie = df[df['title'] == title_name]
    
    # title_named을 가진 DataFrame의 index 객체를 ndarray로 반환하고
    # sorted_ind 인자로 입력된 genre_sim_sorted_ind 객체에서 유사도 순으로 top_n개의 index 추출
    title_index = title_movie.index.values
    similar_indexes = sorted_ind[title_index, :(top_n)]
    
    # 추출된 top_n index 출력, top_n index는 2차원 데이터임
    # dataframe에서 index로 사용하기 위해서 1차원 array로 변경
    print(similar_indexes)
    similar_indexes = similar_indexes.reshape(-1)
    
    return df.iloc[similar_indexes]

In [27]:
similar_movies = find_sim_movie(movies_df, genre_sim_sorted_ind, 'The Godfather', 10)
similar_movies[['title', 'vote_average']]

[[2731 1243 3636 1946 2640 4065 1847 4217  883 3866]]

                                               title  vote_average
2731                          The Godfather: Part II           8.3
1243                                    Mean Streets           7.2
3636                                   Light Sleeper           5.7
1946  The Bad Lieutenant: Port of Call - New Orleans           6.0
2640         Things to Do in Denver When You're Dead           6.7
4065                                      Mi America           0.0
1847                                      GoodFellas           8.2
4217                                            Kids           6.8
883                              Catch Me If You Can           7.7
3866                                     City of God           8.1

In [28]:
movies_df[['title', 'vote_average', 'vote_count']].sort_values('vote_average', ascending=False)[:10]

                         title  vote_average  vote_count
3519          Stiff Upper Lips          10.0           1
4247     Me You and Five Bucks          10.0           2
4045     Dancer, Texas Pop. 81          10.0           1
4662            Little Big Top          10.0           1
3992                 Sardaarji           9.5           2
2386            One Man's Hero           9.3           2
2970        There Goes My Baby           8.5           2
1881  The Shawshank Redemption           8.5        8205
2796     The Prisoner of Zenda           8.4          11
3337             The Godfather           8.4        5893

In [29]:
C = movies_df['vote_average'].mean()
m = movies_df['vote_count'].quantile(0.6)
print('C:', round(C, 3), 'm:', round(m, 3))

C: 6.092 m: 370.2

In [33]:
percentile = 0.6
m = movies_df['vote_count'].quantile(percentile)
C = movies_df['vote_average'].mean()

def weighted_vote_average(record):
    v = record['vote_count']
    R = record['vote_average']
    
    return ( (v/(v+m) * R) + ( (m/(m+v)) * C) )

movies_df['weighted_vote'] = movies.apply(weighted_vote_average, axis=1)

In [34]:
movies_df[['title', 'vote_average', 'weighted_vote', 'vote_count']].sort_values('weighted_vote', ascending=False)[:10]

                         title  vote_average  weighted_vote  vote_count
1881  The Shawshank Redemption           8.5       8.396052        8205
3337             The Godfather           8.4       8.263591        5893
662                 Fight Club           8.3       8.216455        9413
3232              Pulp Fiction           8.3       8.207102        8428
65             The Dark Knight           8.2       8.136930       12002
1818          Schindler's List           8.3       8.126069        4329
3865                  Whiplash           8.3       8.123248        4254
809               Forrest Gump           8.2       8.105954        7927
2294             Spirited Away           8.3       8.105867        3840
2731    The Godfather: Part II           8.3       8.079586        3338

In [35]:
def find_sim_movie(df, sorted_ind, title_name, top_n=10):
    title_movie = df[df['title'] == title_name]
    title_index = title_movie.index.values
    
    # top_n의 2배에 해당하는 장르 유사성이 높은 인덱스 추출
    similar_indexes = sorted_ind[title_index, :(top_n*2)]
    similar_indexes = similar_indexes.reshape(-1)
    # 기준 영화 인덱스는 제외
    similar_indexes = similar_indexes[similar_indexes != title_index]
    
    # top_n의 2배에 해당하는 후보군에서 weighted_vote가 높은 순으로 top_n만큼 추출
    return df.iloc[similar_indexes].sort_values('weighted_vote', ascending=False)[:top_n]

similar_movies = find_sim_movie(movies_df, genre_sim_sorted_ind, 'The Godfather', 10)
similar_movies[['title', 'vote_average', 'weighted_vote']]

                            title  vote_average  weighted_vote
2731       The Godfather: Part II           8.3       8.079586
1847                   GoodFellas           8.2       7.976937
3866                  City of God           8.1       7.759693
1663  Once Upon a Time in America           8.2       7.657811
883           Catch Me If You Can           7.7       7.557097
281             American Gangster           7.4       7.141396
4041              This Is England           7.4       6.739664
1149              American Hustle           6.8       6.717525
1243                 Mean Streets           7.2       6.626569
2839                     Rounders           6.9       6.530427

In [36]:
import pandas as pd
import numpy as np

movies = pd.read_csv('./movies.csv')
ratings = pd.read_csv('./ratings.csv')
print(movies.shape)
print(ratings.shape)

(9742, 3)
(100836, 4)

In [39]:
ratings = ratings[['userId', 'movieId', 'rating']]
ratings_matrix = ratings.pivot_table('rating', index='userId', columns='movieId')
ratings_matrix.head(3)

movieId,1,2,3,4,5,6,7,8,9,10,...,193565,193567,193571,193573,193579,193581,193583,193585,193587,193609
userId,,,,,,,,,,,,,,,,,,,,,
1,4.0,NaN,4.0,NaN,NaN,4.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [41]:
# title 칼럼을 얻기 위해 movies와 조인
rating_movies = pd.merge(ratings, movies, on='movieId')

# columns='title'로 title 칼럼으로 피벗 수행
ratings_matrix = rating_movies.pivot_table('rating', index='userId', columns='title')

# NaN 값을 모두 0으로 변환
ratings_matrix = ratings_matrix.fillna(0)
ratings_matrix.head(3)

title,'71 (2014),'Hellboy': The Seeds of Creation (2004),'Round Midnight (1986),'Salem's Lot (2004),'Til There Was You (1997),'Tis the Season for Love (2015),"'burbs, The (1989)",'night Mother (1986),(500) Days of Summer (2009),*batteries not included (1987),...,Zulu (2013),[REC] (2007),[REC]² (2009),[REC]³ 3 Génesis (2012),anohana: The Flower We Saw That Day - The Movie (2013),eXistenZ (1999),xXx (2002),xXx: State of the Union (2005),¡Three Amigos! (1986),À nous la liberté (Freedom for Us) (1931)
userId,,,,,,,,,,,,,,,,,,,,,
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [42]:
ratings_matrix_T = ratings_matrix.transpose()
ratings_matrix_T.head(3)

userId,1,2,3,4,5,6,7,8,9,10,...,601,602,603,604,605,606,607,608,609,610
title,,,,,,,,,,,,,,,,,,,,,
'71 (2014),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0
'Hellboy': The Seeds of Creation (2004),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
'Round Midnight (1986),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [43]:
from sklearn.metrics.pairwise import cosine_similarity

item_sim = cosine_similarity(ratings_matrix_T, ratings_matrix_T)

# cosine_similarity()로 반환된 넘파이 행렬을 영화명을 매핑해 DataFrame으로 변환
item_sim_df = pd.DataFrame(data=item_sim, index=ratings_matrix.columns, columns=ratings_matrix.columns)

print(item_sim_df)
item_sim_df.head(3)

title                                      '71 (2014)  \
title
'71 (2014)                                   1.000000
'Hellboy': The Seeds of Creation (2004)      0.000000
'Round Midnight (1986)                       0.000000
'Salem's Lot (2004)                          0.000000
'Til There Was You (1997)                    0.000000
...                                               ...
eXistenZ (1999)                              0.000000
xXx (2002)                                   0.139431
xXx: State of the Union (2005)               0.327327
¡Three Amigos! (1986)                        0.000000
À nous la liberté (Freedom for Us) (1931)    0.000000

title                                      'Hellboy': The Seeds of Creation (2004)  \
title
'71 (2014)                                                                0.000000
'Hellboy': The Seeds of Creation (2004)                                   1.000000
'Round Midnight (1986)                                                    0.707107
'Salem's Lot (2004)                                                       0.000000
'Til There Was You (1997)                                                 0.000000
...                                                                            ...
eXistenZ (1999)                                                           0.000000
xXx (2002)                                                                0.000000
xXx: State of the Union (2005)                                            0.000000
¡Three Amigos! (1986)                                                     0.000000
À nous la liberté (Freedom for Us) (1931)                                 0.000000

title                                      'Round Midnight (1986)  \
title
'71 (2014)                                               0.000000
'Hellboy': The Seeds of Creation (2004)                  0.707107
'Round Midnight (1986)                                   1.000000
'Salem's Lot (2004)                                      0.000000
'Til There Was You (1997)                                0.000000
...                                                           ...
eXistenZ (1999)                                          0.000000
xXx (2002)                                               0.000000
xXx: State of the Union (2005)                           0.000000
¡Three Amigos! (1986)                                    0.000000
À nous la liberté (Freedom for Us) (1931)                0.000000

title                                      'Salem's Lot (2004)  \
title
'71 (2014)                                            0.000000
'Hellboy': The Seeds of Creation (2004)               0.000000
'Round Midnight (1986)                                0.000000
'Salem's Lot (2004)                                   1.000000
'Til There Was You (1997)                             0.857493
...                                                        ...
eXistenZ (1999)                                       0.000000
xXx (2002)                                            0.000000
xXx: State of the Union (2005)                        0.000000
¡Three Amigos! (1986)                                 0.000000
À nous la liberté (Freedom for Us) (1931)             0.000000

title                                      'Til There Was You (1997)  \
title
'71 (2014)                                                  0.000000
'Hellboy': The Seeds of Creation (2004)                     0.000000
'Round Midnight (1986)                                      0.000000
'Salem's Lot (2004)                                         0.857493
'Til There Was You (1997)                                   1.000000
...                                                              ...
eXistenZ (1999)                                             0.000000
xXx (2002)                                                  0.000000
xXx: State of the Union (2005)                              0.000000
¡Three Amigos! (1986)                                       0.000000
À nous la liberté (Freedom for Us) (1931)                   0.000000

title                                      'Tis the Season for Love (2015)  \
title
'71 (2014)                                                             0.0
'Hellboy': The Seeds of Creation (2004)                                0.0
'Round Midnight (1986)                                                 0.0
'Salem's Lot (2004)                                                    0.0
'Til There Was You (1997)                                              0.0
...                                                                    ...
eXistenZ (1999)                                                        0.0
xXx (2002)                                                             0.0
xXx: State of the Union (2005)                                         0.0
¡Three Amigos! (1986)                                                  0.0
À nous la liberté (Freedom for Us) (1931)                              0.0

title                                      'burbs, The (1989)  \
title
'71 (2014)                                           0.000000
'Hellboy': The Seeds of Creation (2004)              0.000000
'Round Midnight (1986)                               0.176777
'Salem's Lot (2004)                                  0.000000
'Til There Was You (1997)                            0.000000
...                                                       ...
eXistenZ (1999)                                      0.211467
xXx (2002)                                           0.089634
xXx: State of the Union (2005)                       0.000000
¡Three Amigos! (1986)                                0.372876
À nous la liberté (Freedom for Us) (1931)            0.000000

title                                      'night Mother (1986)  \
title
'71 (2014)                                             0.000000
'Hellboy': The Seeds of Creation (2004)                0.000000
'Round Midnight (1986)                                 0.000000
'Salem's Lot (2004)                                    0.000000
'Til There Was You (1997)                              0.000000
...                                                         ...
eXistenZ (1999)                                        0.216295
xXx (2002)                                             0.000000
xXx: State of the Union (2005)                         0.000000
¡Three Amigos! (1986)                                  0.180009
À nous la liberté (Freedom for Us) (1931)              0.000000

title                                      (500) Days of Summer (2009)  \
title
'71 (2014)                                                    0.141653
'Hellboy': The Seeds of Creation (2004)                       0.000000
'Round Midnight (1986)                                        0.000000
'Salem's Lot (2004)                                           0.000000
'Til There Was You (1997)                                     0.000000
...                                                                ...
eXistenZ (1999)                                               0.097935
xXx (2002)                                                    0.276512
xXx: State of the Union (2005)                                0.156764
¡Three Amigos! (1986)                                         0.169385
À nous la liberté (Freedom for Us) (1931)                     0.000000

title                                      *batteries not included (1987)  \
title
'71 (2014)                                                       0.000000
'Hellboy': The Seeds of Creation (2004)                          0.000000
'Round Midnight (1986)                                           0.000000
'Salem's Lot (2004)                                              0.000000
'Til There Was You (1997)                                        0.000000
...                                                                   ...
eXistenZ (1999)                                                  0.132489
xXx (2002)                                                       0.019862
xXx: State of the Union (2005)                                   0.000000
¡Three Amigos! (1986)                                            0.249586
À nous la liberté (Freedom for Us) (1931)                        0.000000

title                                      ...  Zulu (2013)  [REC] (2007)  \
title                                      ...
'71 (2014)                                 ...     0.000000      0.342055
'Hellboy': The Seeds of Creation (2004)    ...     0.000000      0.000000
'Round Midnight (1986)                     ...     0.000000      0.000000
'Salem's Lot (2004)                        ...     0.000000      0.000000
'Til There Was You (1997)                  ...     0.000000      0.000000
...                                        ...          ...           ...
eXistenZ (1999)                            ...     0.000000      0.000000
xXx (2002)                                 ...     0.069716      0.305535
xXx: State of the Union (2005)             ...     0.000000      0.382543
¡Three Amigos! (1986)                      ...     0.180009      0.000000
À nous la liberté (Freedom for Us) (1931)  ...     0.000000      0.000000

title                                      [REC]² (2009)  \
title
'71 (2014)                                      0.543305
'Hellboy': The Seeds of Creation (2004)         0.000000
'Round Midnight (1986)                          0.000000
'Salem's Lot (2004)                             0.000000
'Til There Was You (1997)                       0.000000
...                                                  ...
eXistenZ (1999)                                 0.000000
xXx (2002)                                      0.173151
xXx: State of the Union (2005)                  0.177838
¡Three Amigos! (1986)                           0.000000
À nous la liberté (Freedom for Us) (1931)       0.000000

title                                      [REC]³ 3 Génesis (2012)  \
title
'71 (2014)                                                0.707107
'Hellboy': The Seeds of Creation (2004)                   0.000000
'Round Midnight (1986)                                    0.000000
'Salem's Lot (2004)                                       0.000000
'Til There Was You (1997)                                 0.000000
...                                                            ...
eXistenZ (1999)                                           0.000000
xXx (2002)                                                0.246482
xXx: State of the Union (2005)                            0.231455
¡Three Amigos! (1986)                                     0.000000
À nous la liberté (Freedom for Us) (1931)                 0.000000

title                                      anohana: The Flower We Saw That Day - The Movie (2013)  \
title
'71 (2014)                                                                                    0.0
'Hellboy': The Seeds of Creation (2004)                                                       0.0
'Round Midnight (1986)                                                                        0.0
'Salem's Lot (2004)                                                                           0.0
'Til There Was You (1997)                                                                     0.0
...                                                                                           ...
eXistenZ (1999)                                                                               0.0
xXx (2002)                                                                                    0.0
xXx: State of the Union (2005)                                                                0.0
¡Three Amigos! (1986)                                                                         0.0
À nous la liberté (Freedom for Us) (1931)                                                     0.0

title                                      eXistenZ (1999)  xXx (2002)  \
title
'71 (2014)                                        0.000000    0.139431
'Hellboy': The Seeds of Creation (2004)           0.000000    0.000000
'Round Midnight (1986)                            0.000000    0.000000
'Salem's Lot (2004)                               0.000000    0.000000
'Til There Was You (1997)                         0.000000    0.000000
...                                                    ...         ...
eXistenZ (1999)                                   1.000000    0.192259
xXx (2002)                                        0.192259    1.000000
xXx: State of the Union (2005)                    0.000000    0.270034
¡Three Amigos! (1986)                             0.170341    0.100396
À nous la liberté (Freedom for Us) (1931)         0.000000    0.000000

title                                      xXx: State of the Union (2005)  \
title
'71 (2014)                                                       0.327327
'Hellboy': The Seeds of Creation (2004)                          0.000000
'Round Midnight (1986)                                           0.000000
'Salem's Lot (2004)                                              0.000000
'Til There Was You (1997)                                        0.000000
...                                                                   ...
eXistenZ (1999)                                                  0.000000
xXx (2002)                                                       0.270034
xXx: State of the Union (2005)                                   1.000000
¡Three Amigos! (1986)                                            0.000000
À nous la liberté (Freedom for Us) (1931)                        0.000000

title                                      ¡Three Amigos! (1986)  \
title
'71 (2014)                                              0.000000
'Hellboy': The Seeds of Creation (2004)                 0.000000
'Round Midnight (1986)                                  0.000000
'Salem's Lot (2004)                                     0.000000
'Til There Was You (1997)                               0.000000
...                                                          ...
eXistenZ (1999)                                         0.170341
xXx (2002)                                              0.100396
xXx: State of the Union (2005)                          0.000000
¡Three Amigos! (1986)                                   1.000000
À nous la liberté (Freedom for Us) (1931)               0.000000

title                                      À nous la liberté (Freedom for Us) (1931)
title
'71 (2014)                                                                       0.0
'Hellboy': The Seeds of Creation (2004)                                          0.0
'Round Midnight (1986)                                                           0.0
'Salem's Lot (2004)                                                              0.0
'Til There Was You (1997)                                                        0.0
...                                                                              ...
eXistenZ (1999)                                                                  0.0
xXx (2002)                                                                       0.0
xXx: State of the Union (2005)                                                   0.0
¡Three Amigos! (1986)                                                            0.0
À nous la liberté (Freedom for Us) (1931)                                        1.0

[9719 rows x 9719 columns]

title,'71 (2014),'Hellboy': The Seeds of Creation (2004),'Round Midnight (1986),'Salem's Lot (2004),'Til There Was You (1997),'Tis the Season for Love (2015),"'burbs, The (1989)",'night Mother (1986),(500) Days of Summer (2009),*batteries not included (1987),...,Zulu (2013),[REC] (2007),[REC]² (2009),[REC]³ 3 Génesis (2012),anohana: The Flower We Saw That Day - The Movie (2013),eXistenZ (1999),xXx (2002),xXx: State of the Union (2005),¡Three Amigos! (1986),À nous la liberté (Freedom for Us) (1931)
title,,,,,,,,,,,,,,,,,,,,,
'71 (2014),1.0,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.0,0.141653,0.0,...,0.0,0.342055,0.543305,0.707107,0.0,0.0,0.139431,0.327327,0.0,0.0
'Hellboy': The Seeds of Creation (2004),0.0,1.000000,0.707107,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,...,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.0
'Round Midnight (1986),0.0,0.707107,1.000000,0.0,0.0,0.0,0.176777,0.0,0.000000,0.0,...,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.0

In [44]:
item_sim_df['Godfather, The (1972)'].sort_values(ascending=False)[:6]

title
Godfather, The (1972)                        1.000000
Godfather: Part II, The (1974)               0.821773
Goodfellas (1990)                            0.664841
One Flew Over the Cuckoo's Nest (1975)       0.620536
Star Wars: Episode IV - A New Hope (1977)    0.595317
Fargo (1996)                                 0.588614
Name: Godfather, The (1972), dtype: float64

In [46]:
item_sim_df['Inception (2010)'].sort_values(ascending=False)[1:6]

title
Dark Knight, The (2008)          0.727263
Inglourious Basterds (2009)      0.646103
Shutter Island (2010)            0.617736
Dark Knight Rises, The (2012)    0.617504
Fight Club (1999)                0.615417
Name: Inception (2010), dtype: float64

In [47]:
def predict_rating(ratings_arr, item_sim_arr):
    ratings_pred = ratings_arr.dot(item_sim_arr) / np.array([np.abs(item_sim_arr).sum(axis=1)])
    return ratings_pred

In [49]:
ratings_pred = predict_rating(ratings_matrix.values, item_sim_df.values)
ratings_pred_matrix = pd.DataFrame(data=ratings_pred, index=ratings_matrix.index, columns=ratings_matrix.columns)
ratings_pred_matrix.head(3)

title,'71 (2014),'Hellboy': The Seeds of Creation (2004),'Round Midnight (1986),'Salem's Lot (2004),'Til There Was You (1997),'Tis the Season for Love (2015),"'burbs, The (1989)",'night Mother (1986),(500) Days of Summer (2009),*batteries not included (1987),...,Zulu (2013),[REC] (2007),[REC]² (2009),[REC]³ 3 Génesis (2012),anohana: The Flower We Saw That Day - The Movie (2013),eXistenZ (1999),xXx (2002),xXx: State of the Union (2005),¡Three Amigos! (1986),À nous la liberté (Freedom for Us) (1931)
userId,,,,,,,,,,,,,,,,,,,,,
1,0.070345,0.577855,0.321696,0.227055,0.206958,0.194615,0.249883,0.102542,0.157084,0.178197,...,0.113608,0.181738,0.133962,0.128574,0.006179,0.212070,0.192921,0.136024,0.292955,0.720347
2,0.018260,0.042744,0.018861,0.000000,0.000000,0.035995,0.013413,0.002314,0.032213,0.014863,...,0.015640,0.020855,0.020119,0.015745,0.049983,0.014876,0.021616,0.024528,0.017563,0.000000
3,0.011884,0.030279,0.064437,0.003762,0.003749,0.002722,0.014625,0.002085,0.005666,0.006272,...,0.006923,0.011665,0.011800,0.012225,0.000000,0.008194,0.007017,0.009229,0.010420,0.084501

In [50]:
from sklearn.metrics import mean_squared_error

# 사용자가 평점을 부여한 영화에 대해서만 예측 성능 평가 MSE를 구함
def get_mse(pred, actual):
    # 평점이 있는 실제 영화만 추출
    pred = pred[actual.nonzero()].flatten()
    actual = actual[actual.nonzero()].flatten()
    return mean_squared_error(pred, actual)

print('아이템 기반 모든 최근접 이웃 MSE: ', get_mse(ratings_pred, ratings_matrix.values))

아이템 기반 모든 최근접 이웃 MSE:  9.895354759094706

In [51]:
def predict_rating_topsim(ratings_arr, item_sim_arr, n=20):
    # 사용자-아이템 평점 행렬 크기만큼 0으로 채운 예측 행렬 초기화
    pred = np.zeros(ratings_arr.shape)
    
    # 사용자-아이템 평점 행렬의 열 크기만큼 루프 수행
    for col in range(ratings_arr.shape[1]):
        # 유사도 행렬에서 유사도가 큰 순으로 n개 데이터 행렬의 인덱스 반환
        top_n_items = [np.argsort(item_sim_arr[:, col])[:-n-1:-1]]
        # 개인화된 예측 평점을 계산
        for row in range(ratings_arr.shape[0]):
            pred[row, col] = item_sim_arr[col, :][top_n_items].dot(ratings_arr[row, :][top_n_items].T)
            pred[row, col] /= np.sum(np.abs(item_sim_arr[col, :][top_n_items]))
            
    return pred

In [52]:
ratings_pred = predict_rating_topsim(ratings_matrix.values, item_sim_df.values, n=20)
print('아이템 기반 최근접 TOP-20 이웃 MSE: ', get_mse(ratings_pred, ratings_matrix.values))

# 계산된 예측 평점 데이터는 DataFrame으로 재생성
ratings_pred_matrix = pd.DataFrame(data=ratings_pred, index=ratings_matrix.index, columns=ratings_matrix.columns)

아이템 기반 최근접 TOP-20 이웃 MSE:  3.695009387428144

In [53]:
user_rating_id = ratings_matrix.loc[9, :]
user_rating_id[user_rating_id > 0].sort_values(ascending=False)[:10]

title
Adaptation (2002)                                                                 5.0
Austin Powers in Goldmember (2002)                                                5.0
Lord of the Rings: The Fellowship of the Ring, The (2001)                         5.0
Lord of the Rings: The Two Towers, The (2002)                                     5.0
Producers, The (1968)                                                             5.0
Citizen Kane (1941)                                                               5.0
Raiders of the Lost Ark (Indiana Jones and the Raiders of the Lost Ark) (1981)    5.0
Back to the Future (1985)                                                         5.0
Glengarry Glen Ross (1992)                                                        4.0
Sunset Blvd. (a.k.a. Sunset Boulevard) (1950)                                     4.0
Name: 9, dtype: float64

In [54]:
def get_unseen_movies(ratings_matrix, userId):
    # userId롤 입력받은 사용자의 모든 영화 정보를 추출해 Series로 반환함
    # 반환된 user_rating은 영화명(title)을 인덱스로 가지는 Series 객체임
    user_rating = ratings_matrix.loc[userId, :]
    
    # user_rating이 0보다 크면 기존에 관람한 영화임 / 대상 인덱스를 추출해 list 객체로 만듦
    already_seen = user_rating[user_rating>0].index.tolist()
    
    # 모든 영화명을 list 객체로 만듦
    movies_list = ratings_matrix.columns.tolist()
    
    # list comprehension으로 already_seen에 해당하는 영화는 movies_list에서 제외함
    unseen_list = [movie for movie in movies_list if movie not in already_seen]
    
    return unseen_list

In [55]:
def recomm_movie_by_userid(pred_df, userId, unseen_list, top_n=10):
    # 예측 평점 DataFrame에서 사용자id 인덱스와 unseen_list로 들어온 영화명 칼럼을 추출해
    # 가장 예측 평점이 높은 순으로 정렬함
    recomm_movies = pred_df.loc[userId, unseen_list].sort_values(ascending=False)[:top_n]
    return recomm_movies

# 사용자가 관람하지 않는 영화명 추출
unseen_list = get_unseen_movies(ratings_matrix, 9)

# 아이템 기반의 최근접 이웃 협업 필터링으로 영화 추천
recomm_movies = recomm_movie_by_userid(ratings_pred_matrix, 9, unseen_list, top_n=10)

# 평점 데이터를 DataFrame으로 생성
recomm_movies = pd.DataFrame(data=recomm_movies.values, index=recomm_movies.index, columns=['pred_score'])

recomm_movies

                                                                                                pred_score
title
Shrek (2001)                                                                                      0.866202
Spider-Man (2002)                                                                                 0.857854
Last Samurai, The (2003)                                                                          0.817473
Indiana Jones and the Temple of Doom (1984)                                                       0.816626
Matrix Reloaded, The (2003)                                                                       0.800990
Harry Potter and the Sorcerer's Stone (a.k.a. Harry Potter and the Philosopher's Stone) (2001)    0.765159
Gladiator (2000)                                                                                  0.740956
Matrix, The (1999)                                                                                0.732693
Pirates of the Caribbean: The Curse of the Black Pearl (2003)                                     0.689591
Lord of the Rings: The Return of the King, The (2003)                                             0.676711